### ISSUE TITLE
Execute in command line

### ISSUE THREAD

**Issue by ElibarikiJ** [grafana/xk6-output-influxdb#15]
ERRO[0000] The moduleSpecifier "samples/http_2.js" couldn't be found on local disk. Make sure that you've specified the right path to the file. If you're running k6 using the Docker image make sure you have mounted the local directory (-v /local/path/:/inside/docker/path) containing your script and modules so that they're accessible by k6 from inside of the container, see https://k6.io/docs/using-k6/modules#using-local-modules-with-docker. Additionally it was tried to be loaded as remote module by prepending "https://" to it, which also didn't work. Remote resolution error: "Get "https://samples/http_2.js": dial tcp: lookup samples on 127.0.0.11:53: no such host"

**Comment by codebien** [comment]
Hi @ElibarikiJ,
if you are trying to run a local script this is an expected error, you should provide a local path.

```
k6 run ./samples/http_2.js
```

I close this issue, feel free to reopen if it is needed.
