### ISSUE TITLE
Discuss whether to not move some fields to be int

### ISSUE THREAD

**Issue by MStoykov** [grafana/xk6-output-influxdb#4]
This was previously discussed when field types were added, but we didn't change them as it would [break](https://github.com/grafana/k6/pull/1395#issuecomment-672587974) if used on an influxdb with the same fields but different types. 

Even then I was of the opinion that this might not be so bad given the benefit of all future deployments having more accurate field types, so I guess now is a good time to probably do that?

We might also want to revisit the tag to fields list and see if we should not add some newer tag

**Comment by codebien** [comment]
https://github.com/grafana/k6/blob/83281346ee53e0ad6755b23590040cc872b79470/stats/system_tag.go#L85-L113

We have several default tags, I think all of them should be fields, in this way we should reduce the default overload on maintaining indexes for InfluxDB. In the end, if the user needs more they can be enabled.

This is my proposal for default tags pushed as tags: `status, method?, scenario, group, check?, error code?`
